### ISSUE TITLE
Check CashBackservice

### ISSUE THREAD

**Issue by Lapeno23** [Lapeno23/CashBackService#1]
Просьба проверить ДЗ

**Comment by coursar** [comment]
@Lapeno23, исправьте открытые Issue + добавьте Travis CI.

**Comment by Lapeno23** [comment]
68367f6e91fcbbe32cecc13bb019ad0ad44d62bc
готово

**Comment by coursar** [comment]
ок, на будущее не забывайте добавлять PMD & SpotBugs
