### ISSUE TITLE
Если используете return нет смысла делать else/else if

### ISSUE THREAD

**Issue by coursar** [Lapeno23/CashBackService#5]
https://github.com/Lapeno23/CashBackService/blob/9ed409b2a472666e4bdb294d50ea766a24842838/src/main/java/ru/itpark/CashBackService.java#L41-L45

Должно быть:
```java
 if (regularCashBack >= maxCashBack) { 
     return maxCashBack; 
 }

return regularCashBack;
```

**Comment by Lapeno23** [comment]
fixed
